### ISSUE TITLE
Some spells with Greater Enduring ability not properly lasting 24 hours when applied by BubbleBuffs

### ISSUE THREAD

**Issue by tjdragon123** [factubsio/BubbleBuffs#11]
**Describe the bug**
Some spells are not properly lasting 24 hours when applied by BubbleBuffs. They still last 24 hours when applied manually. For example, I found that Divine Grace and Death Ward in particular were not working properly.

**To Reproduce**
1. Set Divine Grace (or any of the other bugged spells) to be casted on a party member.
2. Press the buff application button.
3. The buff is applied with only a short duration instead of the proper 24 hour duration.

**Expected behavior**
Applying Divine Grace/Death Ward/etc. should give the same 24 hour duration with Greater Enduring Spells that casting them manually does.

Video demonstration: [https://www.youtube.com/watch?v=Y5uL4kTN21A](https://www.youtube.com/watch?v=Y5uL4kTN21A)

**Comment by factubsio** [comment]
this should be fixed now
