### ISSUE TITLE
Cantrips availability incorrect

### ISSUE THREAD

**Issue by DeadMor0z** [factubsio/BubbleBuffs#2]
**Describe the bug**
When selecting a cantrip to cast (light, for example) - it shows as 0 available, though it should be at will for evrybody who has this cantrip

**Screenshots**
![light](https://user-images.githubusercontent.com/13347404/140623253-37a58e74-f379-4b7f-a263-8a8a093a5d6c.jpg)

**Comment by factubsio** [comment]
Weird. Any other ones not working or just light?

**Comment by DeadMor0z** [comment]
There is a Resistance cantrip, right of Light - it also shows 0+0

**Comment by factubsio** [comment]
I would really appreciate a save. 🥺

**Comment by DeadMor0z** [comment]
Save is not a problem, but I have a lot of mods, some of them a seve-dependant (

**Comment by DeadMor0z** [comment]
Found a problem:
I don't have non-spontaneous casters with cantrips in my party. But for spontaneous casters you add cantrips with credits=spells per day (which is wrong, because it will be always 0)
You're also trying to add custom spells with level 0 - what are they? it shold be metamagiked spells, but they are not applicable for cantrips (0 level spells).

This works fine:
`                        foreach (var spell in book.GetKnownSpells(0)) {
                            ReactiveProperty<int> credits = new ReactiveProperty<int>(500);
                            Main.Verbose($"      Adding cantrip: {spell.Name}", "state");
                            AddBuff(dude, book, spell, null, credits, false, int.MaxValue, characterIndex);
                        }

                        if (book.Blueprint.Spontaneous) {
                            for (int level = 1; level <= book.LastSpellbookLevel; level++) {
                                Main.Verbose($"    Looking at spont level {level}", "state");
                                ReactiveProperty<int> credits = new ReactiveProperty<int>(book.GetSpellsPerDay(level));
                                foreach (var spell in book.GetKnownSpells(level)) {
                                    Main.Verbose($"      Adding spontaneous buff: {spell.Name}", "state");
                                    AddBuff(dude, book, spell, null, credits, false, int.MaxValue, characterIndex);
                                }
                                foreach (var spell in book.GetCustomSpells(level)) {
                                    Main.Verbose($"      Adding spontaneous (customised) buff: {spell.Name}/{dude.CharacterName}", "state");
                                    AddBuff(dude, book, spell, null, credits, false, int.MaxValue, characterIndex);
                                }
                            }
                        } else {
                            foreach (var slot in book.GetAllMemorizedSpells()) {
                                Main.Verbose($"      Adding prepared buff: {slot.Spell.Name}", "state");
                                AddBuff(dude, book, slot.Spell, null, new ReactiveProperty<int>(1), true, int.MaxValue, characterIndex);
                            }
                        }
`

**Comment by DeadMor0z** [comment]
Also, looks like you forgot to set "School Name" label for selected spell.
